[2024-06-07 15:22:20,285][root][INFO] - label_values: [[0, 0]]
[2024-06-07 15:22:20,286][flwr][WARNING] - DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.
            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
[32mINFO[39m:     127.0.0.1:37858 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[2024-06-07 15:22:20,296][flwr][DEBUG] - Opened insecure gRPC connection (no certificates were passed)
[2024-06-07 15:22:20,299][flwr][DEBUG] - ChannelConnectivity.IDLE
[2024-06-07 15:22:20,301][flwr][DEBUG] - ChannelConnectivity.CONNECTING
[2024-06-07 15:22:20,305][flwr][DEBUG] - ChannelConnectivity.READY
[2024-06-07 15:22:20,315][flwr][INFO] -
[2024-06-07 15:22:20,316][flwr][INFO] - [RUN 0, ROUND ]
[2024-06-07 15:22:20,316][flwr][INFO] - Received: train message 1f75314f-8ae8-48db-a9d2-bf168f927939
config: {'batch_size': 128, 'local_epochs': 5, 'num_rounds': 5}
Starting training...
[2024-06-07 15:22:20,319][flwr][ERROR] - Client raised an exception.
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
              ^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/client_fl.py", line 135, in fit
    trained_model = self.train_torch(self.model, self.train_loader, self.val_loader, epochs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/models.py", line 29, in custom_train_torch
    for epoch in range(epochs):
                 ^^^^^^^^^^^^^
TypeError: 'DataLoader' object cannot be interpreted as an integer
[2024-06-07 15:22:20,508][flwr][DEBUG] - gRPC channel closed
[2024-06-07 15:22:20,530][root][INFO] - notify_fail start
[2024-06-07 15:22:20,546][root][ERROR] - trainFin
[93mWARNING [39m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.
            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
[92mINFO [39m:
[92mINFO [39m:      [RUN 0, ROUND ]
[92mINFO [39m:      Received: train message 1f75314f-8ae8-48db-a9d2-bf168f927939
[91mERROR [39m:     Client raised an exception.
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
              ^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/client_fl.py", line 135, in fit
    trained_model = self.train_torch(self.model, self.train_loader, self.val_loader, epochs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/models.py", line 29, in custom_train_torch
    for epoch in range(epochs):
                 ^^^^^^^^^^^^^
TypeError: 'DataLoader' object cannot be interpreted as an integer
--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 122, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 643, in start_numpy_client
    start_client(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 291, in start_client
    _start_client_internal(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 503, in _start_client_internal
    raise ex
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
              ^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/client_fl.py", line 135, in fit
    trained_model = self.train_torch(self.model, self.train_loader, self.val_loader, epochs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/models.py", line 29, in custom_train_torch
    for epoch in range(epochs):
                 ^^^^^^^^^^^^^
TypeError: 'DataLoader' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 85, in <module>
    main()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 81, in main
    fl_client.start()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 201, in start
    uvicorn.run(self.app, host='0.0.0.0', port=self.client_port)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/responses.py", line 156, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 158, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (TypeError("'DataLoader' object cannot be interpreted as an integer"),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 122, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 643, in start_numpy_client
    start_client(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 291, in start_client
    _start_client_internal(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 503, in _start_client_internal
    raise ex
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
              ^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/client_fl.py", line 135, in fit
    trained_model = self.train_torch(self.model, self.train_loader, self.val_loader, epochs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/models.py", line 29, in custom_train_torch
    for epoch in range(epochs):
                 ^^^^^^^^^^^^^
TypeError: 'DataLoader' object cannot be interpreted as an integer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 85, in <module>
    main()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 81, in main
    fl_client.start()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 201, in start
    uvicorn.run(self.app, host='0.0.0.0', port=self.client_port)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/responses.py", line 156, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 158, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (TypeError("'DataLoader' object cannot be interpreted as an integer"),)
[31mERROR[39m:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/responses.py", line 156, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 161, in fl_client_start
    raise e
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 122, in fl_client_start
    await loop.run_in_executor(None, client_start)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 643, in start_numpy_client
    start_client(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 291, in start_client
    _start_client_internal(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 503, in _start_client_internal
    raise ex
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
              ^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/client_fl.py", line 135, in fit
    trained_model = self.train_torch(self.model, self.train_loader, self.val_loader, epochs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/models.py", line 29, in custom_train_torch
    for epoch in range(epochs):
                 ^^^^^^^^^^^^^
TypeError: 'DataLoader' object cannot be interpreted as an integer
[32mINFO[39m:     127.0.0.1:58544 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:39700 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:39704 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:40360 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:50100 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:50110 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:34678 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:43246 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:43252 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:41704 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:53676 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:53682 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:36122 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:51066 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:51070 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:58792 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:41032 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:41040 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:48924 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:48932 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:43046 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:43960 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:43972 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:39012 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:49164 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:49168 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:58856 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:42938 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:42942 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:57046 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:36048 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:36054 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:40498 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:59170 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:59178 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:50364 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:45392 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:45398 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:44956 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:36770 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:36778 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:42764 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:42778 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:33374 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:60004 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:60016 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:40644 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:38744 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:38754 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:59662 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:48178 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:48186 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:57684 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:41632 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:41640 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     Shutting down
[32mINFO[39m:     Waiting for application shutdown.
[32mINFO[39m:     Application shutdown complete.
[32mINFO[39m:     Finished server process [[36m1896085[39m]
[2024-06-07 15:28:23,791][root][INFO] - ccl-y-server;f0:2f:74:96:d6:64-client close