--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 112, in fl_client_start
    label_values = [[i, self.y_label_counter[i]] for i in range(self.output_size)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 112, in <listcomp>
    label_values = [[i, self.y_label_counter[i]] for i in range(self.output_size)]
                        ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'int' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 84, in <module>
    main()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 80, in main
    fl_client.start()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 201, in start
    uvicorn.run(self.app, host='0.0.0.0', port=self.client_port)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/responses.py", line 156, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 158, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (TypeError("'int' object is not subscriptable"),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 112, in fl_client_start
    label_values = [[i, self.y_label_counter[i]] for i in range(self.output_size)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 112, in <listcomp>
    label_values = [[i, self.y_label_counter[i]] for i in range(self.output_size)]
                        ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'int' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 84, in <module>
    main()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ccl/Desktop/isfolder/issrc/fedops/FedOps-ADMET2/client_main.py", line 80, in main
    fl_client.start()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 201, in start
    uvicorn.run(self.app, host='0.0.0.0', port=self.client_port)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/responses.py", line 156, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 158, in fl_client_start
    logging.info('[E][PC0002] learning', e)
Message: '[E][PC0002] learning'
Arguments: (TypeError("'int' object is not subscriptable"),)
[31mERROR[39m:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    await response(scope, receive, send)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/responses.py", line 156, in __call__
    await self.background()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 161, in fl_client_start
    raise e
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 112, in fl_client_start
    label_values = [[i, self.y_label_counter[i]] for i in range(self.output_size)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ccl/anaconda3/envs/isenv/lib/python3.11/site-packages/fedops/client/app.py", line 112, in <listcomp>
    label_values = [[i, self.y_label_counter[i]] for i in range(self.output_size)]
                        ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'int' object is not subscriptable
[2024-06-07 15:11:38,272][root][INFO] - notify_fail start
[32mINFO[39m:     127.0.0.1:50988 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[2024-06-07 15:11:38,303][root][ERROR] - trainFin
[32mINFO[39m:     127.0.0.1:40374 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:37888 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:37902 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:47762 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:47768 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:38288 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:49262 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:49266 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:50742 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:58682 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:58688 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:34950 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:49442 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:49452 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     127.0.0.1:35820 - "[1mGET /online HTTP/1.1[22m" [32m200 OK
[32mINFO[39m:     Shutting down
[32mINFO[39m:     Waiting for application shutdown.
[32mINFO[39m:     Application shutdown complete.
[32mINFO[39m:     Finished server process [[36m1879597[39m]
[2024-06-07 15:13:19,014][root][INFO] - ccl-y-server;f0:2f:74:96:d6:64-client close